# Generated by Django 4.2.8 on 2026-01-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échec'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='orders_emai_order_i_3a31c6_idx'), models.Index(fields=['-sent_at'], name='orders_emai_sent_at_17f136_idx')],
            },
        ),
    ]
