# Generated by Django 4.2.8 on 2026-01-10 22:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='building_apartment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Building/Apartment Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Instructions'),
        ),
        migrations.AddField(
            model_name='address',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer_tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20, verbose_name='Customer Tier'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_order_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Order At'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Loyalty Points'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('XOF', 'CFA Franc')], default='EUR', max_length=3, verbose_name='Preferred Currency'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='receive_order_notifications',
            field=models.BooleanField(default=True, verbose_name='Receive Order Notifications'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='receive_promotional_emails',
            field=models.BooleanField(default=True, verbose_name='Receive Promotional Emails'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='subscribe_to_newsletter',
            field=models.BooleanField(default=True, verbose_name='Subscribe to Newsletter'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Orders'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Spent'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default_billing',
            field=models.BooleanField(default=False, verbose_name='Default Billing Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default_shipping',
            field=models.BooleanField(default=False, verbose_name='Default Shipping Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='Home', max_length=100, verbose_name='Address Label'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user'], name='customers_a_user_id_68d07a_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_default_shipping'], name='customers_a_is_defa_1cbb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_default_billing'], name='customers_a_is_defa_00593c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['user'], name='customers_c_user_id_b45f28_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['customer_tier'], name='customers_c_custome_4ad75b_idx'),
        ),
    ]
