# Generated by Django 6.0.1 on 2026-01-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('seller', 'Seller'), ('customer', 'Customer'), ('courier', 'Courier')], default='seller', max_length=20),
        ),
    ]
