# Generated by Django 4.2.8 on 2026-01-10 22:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='approval_note',
            field=models.TextField(blank=True, null=True, verbose_name='Approval Note'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('banned', 'Banned')], db_index=True, default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sellers', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='auto_accept_returns',
            field=models.BooleanField(default=False, verbose_name='Auto Accept Returns'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Account Holder Name'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Code (SWIFT/BIC)'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Country'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Routing Number'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='building_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Building/Suite Number'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Registration Number'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Registered Business'), ('corporate', 'Corporate')], default='individual', max_length=20, verbose_name='Business Type'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format', regex='^\\+?1?\\d{9,15}$')], verbose_name='Primary Phone'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='response_time_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Response Time (hours)'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='return_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Return Days Allowed'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_level',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20, verbose_name='Seller Level'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_banner_url',
            field=models.URLField(blank=True, null=True, verbose_name='Shop Banner URL'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Shop Logo URL'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Shop URL Slug'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support Email'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID Number'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Orders'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Products'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Reviews'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email Verified At'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('banned', 'Banned')], db_index=True, default='active', max_length=20, verbose_name='Account Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Two-Factor Authentication Enabled'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('seller', 'Seller'), ('customer', 'Customer'), ('courier', 'Courier')], db_index=True, default='customer', max_length=20, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['approval_status'], name='accounts_se_approva_0747c4_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['user'], name='accounts_se_user_id_15fcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['created_at'], name='accounts_se_created_937d12_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['seller_level'], name='accounts_se_seller__ebae5c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='accounts_us_role_9fc6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
    ]
