# Generated by Django 4.2.8 on 2026-01-10 23:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_sellerprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping Address'), ('billing', 'Billing Address'), ('both', 'Shipping & Billing')], default='shipping', max_length=20, verbose_name='Address Type')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Address')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient Name')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number format', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apartment/Suite Number')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state_province', models.CharField(max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('address_notes', models.TextField(blank=True, null=True, verbose_name='Address Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_role_9fc6ca_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='account_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='biography',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Picture URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'account_status'], name='accounts_us_role_eb3e81_idx'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('user', 'recipient_name')},
        ),
    ]
