# Generated by Django 4.2.8 on 2026-01-11 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraddress_remove_user_accounts_us_role_9fc6ca_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blacklisted_access_tokens',
                'indexes': [models.Index(fields=['jti'], name='blacklisted_jti_4fc565_idx'), models.Index(fields=['user'], name='blacklisted_user_id_53bb2a_idx'), models.Index(fields=['blacklisted_at'], name='blacklisted_blackli_b8e513_idx')],
            },
        ),
    ]
