# Generated by Django 4.2.8 on 2026-01-11 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone'),
        ),
    ]
