# Generated by Django 4.2.8 on 2026-01-10 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_sellerprofile_address_and_more'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deduction Amount'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='deduction_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Deduction Reason'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inspected At'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_returns', to=settings.AUTH_USER_MODEL, verbose_name='Inspected By'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='inspection_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Inspection Notes'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Received At'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Refund Amount'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_returns', to=settings.AUTH_USER_MODEL, verbose_name='Refund Initiated By'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Refund Reason'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Refund Status'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Refunded At'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_carrier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Return Carrier'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_shipping_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Return Shipping Label'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Return Tracking Number'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='accounts.sellerprofile', verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='description',
            field=models.TextField(verbose_name='Return Description'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not As Described'), ('damaged_in_shipping', 'Damaged in Shipping'), ('missing_parts', 'Missing Parts'), ('no_longer_needed', 'No Longer Needed'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], max_length=50, verbose_name='Return Reason'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Responded At'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('initiated', 'Return Initiated'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_return_shipping', 'Pending Return Shipping'), ('in_transit', 'In Transit'), ('received_by_seller', 'Received by Seller'), ('inspection_in_progress', 'Inspection In Progress'), ('inspected', 'Inspected'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=50, verbose_name='Return Status'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='returns_ret_status_d3fc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['refund_status'], name='returns_ret_refund__227b96_idx'),
        ),
    ]
