# Generated by Django 4.2.8 on 2026-01-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnrequest_deduction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('initiated', 'Return Initiated'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_return_shipping', 'Pending Return Shipping'), ('in_transit', 'In Transit'), ('received_by_seller', 'Received by Seller'), ('inspection_in_progress', 'Inspection In Progress'), ('inspected', 'Inspected'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=50, verbose_name='Return Status'),
        ),
    ]
