# Generated by Django 4.2.8 on 2026-01-10 22:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coupon',
            name='promotions__is_acti_a01a21_idx',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applies_to_sale_items',
            field=models.BooleanField(default=True, verbose_name='Applies to Sale Items'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='excluded_categories',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_coupons', to='catalog.category', verbose_name='Excluded Categories'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_stackable',
            field=models.BooleanField(default=False, verbose_name='Stackable with Other Coupons'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Purchase Amount'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Coupon Name'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product', verbose_name='Applicable Products'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='require_email_subscription',
            field=models.BooleanField(default=False, verbose_name='Require Email Subscription'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_used_by_user',
            field=models.PositiveIntegerField(default=0, verbose_name='Times Used by Current User'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Final Amount'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Is Refunded'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Original Amount'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Refund Amount'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Refunded At'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category', verbose_name='Applicable Categories'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Coupon Code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping'), ('buy_one_get_one', 'Buy One Get One')], max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='scope',
            field=models.CharField(choices=[('global', 'Global - All Products'), ('category', 'Category Specific'), ('seller', 'Seller Specific'), ('product', 'Product Specific')], default='global', max_length=20, verbose_name='Coupon Scope'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Used At'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status'], name='promotions__status_791787_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='promotions__is_acti_8daf39_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date', 'end_date'], name='promotions__start_d_4dfb66_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='promotions__coupon__6ff8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user'], name='promotions__user_id_2b7239_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['used_at'], name='promotions__used_at_625b98_idx'),
        ),
    ]
