# Generated by Django 4.2.8 on 2026-01-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=20, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount Percentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='Digital Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='On Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=5, verbose_name='Minimum Stock Alert'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published At'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Shipping Cost'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_type',
            field=models.CharField(choices=[('standard', 'Standard Shipping'), ('express', 'Express Shipping'), ('free', 'Free Shipping'), ('custom', 'Custom Shipping')], default='standard', max_length=20, verbose_name='Shipping Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='Total Reviews'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(default=0, verbose_name='Total Sold'),
        ),
        migrations.AddField(
            model_name='product',
            name='upc_ean',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UPC/EAN'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_featured'], name='catalog_pro_status_70303b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['published_at'], name='catalog_pro_publish_1295c5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['average_rating', 'total_reviews'], name='catalog_pro_average_5206e0_idx'),
        ),
    ]
