# Generated by Django 4.2.8 on 2026-01-10 22:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewhelpful',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review Helpful Vote', 'verbose_name_plural': 'Review Helpful Votes'},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_product_99e47c_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='reviewhelpful',
            name='is_helpful',
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Helpful Count'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Moderated At'),
        ),
        migrations.AddField(
            model_name='review',
            name='order_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Order Reference'),
        ),
        migrations.AddField(
            model_name='review',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Response At'),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_response',
            field=models.TextField(blank=True, null=True, verbose_name='Seller Response'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='review',
            name='unhelpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Unhelpful Count'),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='vote_type',
            field=models.CharField(choices=[('helpful', 'Helpful'), ('unhelpful', 'Unhelpful')], default='helpful', max_length=20, verbose_name='Vote Type'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Review Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Verified Purchase'),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderation_note',
            field=models.TextField(blank=True, null=True, verbose_name='Moderation Note'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Review Title'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='reviewhelpful',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reviewhelpful',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewhelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_helpful_votes', to=settings.AUTH_USER_MODEL, verbose_name='Voter'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status'], name='reviews_rev_product_0aaa55_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase'], name='reviews_rev_is_veri_544d90_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review', 'vote_type'], name='reviews_rev_review__f0c90f_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['user'], name='reviews_rev_user_id_b71125_idx'),
        ),
    ]
